import Foundation

/// Specifies the default filters to be attached to a query before executing it
///
/// The filters generated by this rule are combined with a query's `filter` property
/// using an `and` filter.
public enum BaseFilters: String, Codable, Hashable, Equatable {
    /// Attach test mode filter and filter for all apps of the executing user's organization
    case thisOrganization
    
    /// Attach test mode filter and filter for the app the insight lives in
    ///
    /// This fails if the query does not belong to an insight.
    case thisApp
    
    /// Attach test mode filter and filter for the example app's data
    ///
    /// The server will execute this query as if the owner of the Example App
    /// is logged in, and it will always return example data instead of an
    /// actual user's data.
    ///
    /// This is great for showing a demo of the environment.
    case exampleData
    
    /// Only available for super org, do not specify any filters
    ///
    /// This is used internally for admin dashboards. The server will
    /// throw an error if this is executed by someone who is not a member
    /// of the super org.
    case noFilter
}
